### ISSUE TITLE
Add option to not notify

### ISSUE THREAD

**Issue by kentcdodds** [neotan/vscode-auto-restart-typescript-eslint-servers#1]
I'd love to not get a notification of when the server restarts.

**Comment by neotan** [comment]
working on it

**Comment by kentcdodds** [comment]
Sweet! Thank you!

Just so you know: https://github.com/microsoft/vscode/issues/187208#issuecomment-1643014397

**Comment by neotan** [comment]
Thanks for the issue,  @kentcdodds, the enhanced version had been released, pls update to `v0.0.5` and let me know if it works. Thanks!
https://marketplace.visualstudio.com/items?itemName=neotan.vscode-auto-restart-typescript-eslint-servers
