### ISSUE TITLE
Restarting Client failed error with ESLint

### ISSUE THREAD

**Issue by SerafinDinges** [neotan/vscode-auto-restart-typescript-eslint-servers#10]
Hey! Thanks for this plugin.

Unfortunately restarting the ESLint part of the plugin doesn't seem to work for our team as we get an error when trying to restart the client.

![Screenshot 2024-01-17 at 16 10 07](https://github.com/neotan/vscode-auto-restart-typescript-eslint-servers/assets/1583184/3e964289-ad0d-4e22-9b01-4731d5d5746b)

Any idea? Here's the full stacktrace:

```
[Error - 16:09:55] Restarting client failed
Error: Stopping the server timed out
    at /Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/client/out/extension.js:1:104373
    at w.restart (/Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/client/out/extension.js:1:265414)
[Error - 16:09:56] Server process exited with code 0. This usually indicates a misconfigured ESLint setup.
Error: stack
    at process.exit (/Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:218467)
    at Object.exit (/Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:203376)
    at /Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:192281
    at /Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:54836
    at oe (/Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:55683)
    at /Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:51634
    at Immediate._onImmediate (/Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:51654)
    at process.processImmediate (node:internal/timers:476:21)
```

This happens to everyone in our team. Manually restarting ESLint via the internal VS Code command works fine.

Thank you for any help.

**Comment by neotan** [comment]
Hi @SerafinDinges,
thanks for raising the issue, could you share your vscode info in menu **Help > About** pls?

**Comment by neotan** [comment]
![image](https://github.com/neotan/vscode-auto-restart-typescript-eslint-servers/assets/10399087/38bfb9ba-7efd-46a7-8837-bd2d8c991682)

@SerafinDinges  - interestingly, when I reinstall my extension without any change, it works again, then I checked the `dbaeumer.vscode-eslint` extension, they has an update after you raised this issue. Could you double check if this helps?

**Comment by neotan** [comment]
Closed temporarily, reopen if needed.
