### ISSUE TITLE
Add the option to disable server restart notifications

### ISSUE THREAD

**Issue by Gusarovv** [neotan/vscode-auto-restart-typescript-eslint-servers#5]
Please add it so that I can choose whether to notify or not about the server restart.

**Comment by neotan** [comment]
Duplicate of #1

**Comment by neotan** [comment]
Thanks for the issue,  @Gusarovv, the enhanced version had been released, pls update to `v0.0.5` and let me know if it works. Thanks!
https://marketplace.visualstudio.com/items?itemName=neotan.vscode-auto-restart-typescript-eslint-servers

**Comment by Gusarovv** [comment]
Thanks! I updated the version to v0.0.5. Disabled the notification - it works fine
