### ISSUE TITLE
While on the topic: It would also be nice to avoid restarting ESLint if it isn't running (because no relevant files have been opened yet), as this also creates a notification. I don't know how hard this would be to detect though.

### ISSUE THREAD

**Issue by neotan** [neotan/vscode-auto-restart-typescript-eslint-servers#6]
While on the topic: It would also be nice to avoid restarting ESLint if it isn't running (because no relevant files have been opened yet), as this also creates a notification. I don't know how hard this would be to detect though.

_Originally posted by @ehoogeveen-medweb in https://github.com/neotan/vscode-auto-restart-typescript-eslint-servers/issues/1#issuecomment-1643796570_

**Comment by neotan** [comment]
Thanks for the issue,  @ehoogeveen-medweb, the fixed version had been released, pls update to `v0.0.5`. Thanks!
https://marketplace.visualstudio.com/items?itemName=neotan.vscode-auto-restart-typescript-eslint-servers

**Comment by ehoogeveen-medweb** [comment]
@neotan It looks like this is still happening with v0.0.5: If I modify/re-save `.eslintrc.json` before opening any javascript or typescript files, the following notification pops up:
![image](https://github.com/neotan/vscode-auto-restart-typescript-eslint-servers/assets/55082669/21b71cd1-dcd1-4c6a-bb4a-5ce2bc0b1d5f)
The notification from *this* extension can be disabled via the new setting, but the *ESLint* extension doesn't like the restart.

**Comment by neotan** [comment]
@ehoogeveen-medweb  Thanks for clarifying the symptom! The msg you posted was that bcoz the ESLint server hasn't been fully started, even the [`.isActivate === true`](https://github.com/neotan/vscode-auto-restart-typescript-eslint-servers/blob/694281802de104fbb56c9904e7b814918bf4f616/src/extension.ts#L96)

I can check the open files' extensions to determine if the ESLint server is fully started, but will run into another edge case: the user opens and then closes all the JS/TS files, then this check will be failed.

```js
// Idea: `isJsFileOpen === true` means ESLint server is fully started
  const isJsFileOpen= window.tabGroups.all  
    .flatMap(({ tabs }) => tabs.map(tab => tab.label))
    .some(label => label.match(/(.ts|.tsx|.js|.jsx)$/))
```

So let's treat it as an edge case in the current situation, hopefully, the [vscode-eslint](https://github.com/microsoft/vscode-eslint) can provide a more reliable `isActivate` someday. Again, thanks for your bring this issue up. Cheer🍻!
