### ISSUE TITLE
[feature request] Allow (custom) globs to be arrays

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [neotan/vscode-auto-restart-typescript-eslint-servers#8]
Currently the `fileGlobForESLint` and `fileGlobForTypescript` settings take a string. This leads to duplication as glob groups cannot be nested.

For example, I'm currently using
```json
"**/.eslintrc.{json,default.json,ts.json}"
```
I would like to add `**/package.json` (because `eslint-plugin-import` doesn't handle dependency changes very well), but to do that I currently need to pull the `.eslintrc.` part into the group (although I can then move the `.json` part out):
```json
"**/{.eslintrc,.eslintrc.default,.eslintrc.ts,package}.json"
```

I would prefer to be able to use the following:
```json
["**/.eslintrc.{default,ts}.json", "**/.eslintrc.json", "**/package.json"]
```
or
```json
["**/.eslintrc.{default,ts}.json", "**/{.eslintrc,package}.json"]
```
to minimize the amount of repetition.

**Comment by neotan** [comment]
Thanks @ehoogeveen-medweb for raising this issue. Anyone wanted this feature to be in the next version, pls 👍 his comment. Thx.

**Comment by ffMathy** [comment]
I would love this too!

**Comment by neotan** [comment]
Thanks for your great contributions, @j4k0xb !
The new version [v0.0.6](https://marketplace.visualstudio.com/items?itemName=neotan.vscode-auto-restart-typescript-eslint-servers) is ready, please update and welcome any feedback! 🙏
